-- ============================================================================
-- Script de creacion de la base de datos - Plataforma de Educacion Virtual
-- ============================================================================
-- Refleja el esquema derivado de las entidades JPA del backend (paquete
-- com.bitcriollo.plataforma.model), tal como Hibernate las materializa con
-- spring.jpa.hibernate.ddl-auto=update sobre PostgreSQL.
--
-- No es necesario ejecutar este script para que la aplicacion funcione: al
-- conectarse a una base de datos vacia, Hibernate crea el esquema solo. Este
-- script existe como entregable documental (creacion explicita de la BD) y
-- como alternativa para levantar el esquema sin arrancar el backend.
--
-- Orden de creacion: se respetan las dependencias de llave foranea.
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- usuarios (tabla base de la herencia JOINED: Usuario)
-- ---------------------------------------------------------------------------
CREATE TABLE usuarios (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            VARCHAR(255) NOT NULL,
    apellido          VARCHAR(255) NOT NULL,
    correo            VARCHAR(255) NOT NULL UNIQUE,
    contrasena_hash   VARCHAR(255) NOT NULL,
    telefono          VARCHAR(255),
    foto_perfil_url   VARCHAR(255),
    activo            BOOLEAN NOT NULL DEFAULT TRUE,
    email_verificado  BOOLEAN NOT NULL DEFAULT FALSE,
    ultimo_acceso     TIMESTAMP,
    intentos_fallidos INTEGER NOT NULL DEFAULT 0,
    bloqueado_hasta   TIMESTAMP,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- Subtipos de usuarios (herencia JOINED: id comparte PK con usuarios)
-- ---------------------------------------------------------------------------
CREATE TABLE administradores (
    id           BIGINT PRIMARY KEY REFERENCES usuarios (id),
    codigo       VARCHAR(255) NOT NULL UNIQUE,
    cargo        VARCHAR(255) NOT NULL,
    nivel_acceso VARCHAR(50)  NOT NULL DEFAULT 'ADMIN' -- SUPER_ADMIN | ADMIN
);

CREATE TABLE docentes (
    id                  BIGINT PRIMARY KEY REFERENCES usuarios (id),
    codigo_docente      VARCHAR(255) NOT NULL UNIQUE,
    especialidad        VARCHAR(255) NOT NULL,
    titulo_profesional  VARCHAR(255) NOT NULL,
    anios_experiencia   INTEGER DEFAULT 0,
    biografia           TEXT
);

CREATE TABLE estudiantes (
    id                  BIGINT PRIMARY KEY REFERENCES usuarios (id),
    codigo_estudiantil  VARCHAR(255) NOT NULL UNIQUE,
    tipo_documento      VARCHAR(50)  NOT NULL, -- CEDULA | PASAPORTE | TARJETA_DE_IDENTIDAD
    numero_documento    VARCHAR(255) NOT NULL UNIQUE,
    programa_academico  VARCHAR(255) NOT NULL,
    semestre            INTEGER NOT NULL
);

CREATE TABLE coordinadores_academicos (
    id                BIGINT PRIMARY KEY REFERENCES usuarios (id),
    codigo            VARCHAR(255) NOT NULL UNIQUE,
    facultad          VARCHAR(255) NOT NULL,
    telefono_oficina  VARCHAR(255)
);

-- ---------------------------------------------------------------------------
-- cursos
-- ---------------------------------------------------------------------------
CREATE TABLE cursos (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                  VARCHAR(255) NOT NULL,
    descripcion             TEXT,
    estado                  VARCHAR(50) NOT NULL DEFAULT 'ACTIVO', -- ACTIVO | INACTIVO | ARCHIVADO
    docente_id              BIGINT NOT NULL REFERENCES docentes (id),
    creado_por_usuario_id   BIGINT NOT NULL REFERENCES usuarios (id),
    fecha_inicio            DATE,
    fecha_fin               DATE,
    cupo_maximo             INTEGER,
    imagen_portada_url      VARCHAR(255),
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- lecciones
-- ---------------------------------------------------------------------------
CREATE TABLE lecciones (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curso_id          BIGINT NOT NULL REFERENCES cursos (id),
    titulo            VARCHAR(255) NOT NULL,
    contenido         TEXT,
    tipo_contenido    VARCHAR(50) NOT NULL DEFAULT 'TEXTO', -- VIDEO | TEXTO | PDF | ENLACE
    duracion_minutos  INTEGER,
    orden             INTEGER NOT NULL,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- recursos_bibliograficos
-- ---------------------------------------------------------------------------
CREATE TABLE recursos_bibliograficos (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curso_id          BIGINT NOT NULL REFERENCES cursos (id),
    titulo            VARCHAR(255) NOT NULL,
    autor             VARCHAR(255),
    anio_publicacion  INTEGER,
    tipo_recurso      VARCHAR(50) NOT NULL, -- LIBRO | ARTICULO | VIDEO | ENLACE | DOCUMENTO
    enlace            VARCHAR(255) NOT NULL,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- inscripciones
-- ---------------------------------------------------------------------------
CREATE TABLE inscripciones (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id        BIGINT NOT NULL REFERENCES estudiantes (id),
    curso_id             BIGINT NOT NULL REFERENCES cursos (id),
    estado               VARCHAR(50) NOT NULL DEFAULT 'ACTIVA', -- ACTIVA | COMPLETADA | CANCELADA
    fecha_inscripcion    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    calificacion_final   DOUBLE PRECISION,
    CONSTRAINT uk_inscripcion_estudiante_curso UNIQUE (estudiante_id, curso_id)
);

-- ---------------------------------------------------------------------------
-- progreso_lecciones
-- ---------------------------------------------------------------------------
CREATE TABLE progreso_lecciones (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id      BIGINT NOT NULL REFERENCES estudiantes (id),
    leccion_id         BIGINT NOT NULL REFERENCES lecciones (id),
    completado         BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_completado   TIMESTAMP,
    created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_progreso_estudiante_leccion UNIQUE (estudiante_id, leccion_id)
);

-- ---------------------------------------------------------------------------
-- foros / mensajes_foro
-- ---------------------------------------------------------------------------
CREATE TABLE foros (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curso_id    BIGINT NOT NULL UNIQUE REFERENCES cursos (id),
    titulo      VARCHAR(255),
    descripcion TEXT,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE mensajes_foro (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    foro_id            BIGINT NOT NULL REFERENCES foros (id),
    usuario_id         BIGINT NOT NULL REFERENCES usuarios (id),
    mensaje_padre_id   BIGINT REFERENCES mensajes_foro (id),
    contenido          TEXT NOT NULL,
    editado            BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_publicacion  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- evaluaciones (herencia JOINED: Evaluacion) y sus subtipos
-- ---------------------------------------------------------------------------
CREATE TABLE evaluaciones (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curso_id           BIGINT NOT NULL REFERENCES cursos (id),
    titulo             VARCHAR(255) NOT NULL,
    descripcion        TEXT,
    peso_porcentual    DOUBLE PRECISION NOT NULL,
    estado             VARCHAR(50) NOT NULL DEFAULT 'BORRADOR', -- BORRADOR | PUBLICADA | CERRADA
    fecha_publicacion  TIMESTAMP,
    created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE examenes (
    id                          BIGINT PRIMARY KEY REFERENCES evaluaciones (id),
    fecha_aplicacion            TIMESTAMP NOT NULL,
    tiempo_limite               INTEGER NOT NULL,
    numero_intentos_permitidos  INTEGER NOT NULL DEFAULT 1,
    aleatorio                   BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE tareas (
    id                                 BIGINT PRIMARY KEY REFERENCES evaluaciones (id),
    instrucciones                      TEXT,
    fecha_limite                       TIMESTAMP NOT NULL,
    permite_entrega_tardia             BOOLEAN NOT NULL DEFAULT FALSE,
    penalizacion_tardanza_porcentaje   DOUBLE PRECISION
);

-- ---------------------------------------------------------------------------
-- resultados
-- ---------------------------------------------------------------------------
CREATE TABLE resultados (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluacion_id       BIGINT NOT NULL REFERENCES evaluaciones (id),
    estudiante_id       BIGINT NOT NULL REFERENCES estudiantes (id),
    numero_intento      INTEGER NOT NULL DEFAULT 1,
    calificacion        DOUBLE PRECISION,
    retroalimentacion   TEXT,
    contenido_entrega   TEXT,
    estado              VARCHAR(50) NOT NULL DEFAULT 'PENDIENTE', -- PENDIENTE | CALIFICADO
    fecha_registro      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_resultado_evaluacion_estudiante_intento UNIQUE (evaluacion_id, estudiante_id, numero_intento)
);

-- ---------------------------------------------------------------------------
-- refresh_tokens
-- ---------------------------------------------------------------------------
CREATE TABLE refresh_tokens (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token             VARCHAR(255) NOT NULL UNIQUE,
    usuario_id        BIGINT NOT NULL REFERENCES usuarios (id),
    fecha_expiracion  TIMESTAMP NOT NULL,
    revocado          BOOLEAN NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- log_accesos
-- ---------------------------------------------------------------------------
CREATE TABLE log_accesos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      BIGINT REFERENCES usuarios (id),
    correo_intento  VARCHAR(255) NOT NULL,
    exitoso         BOOLEAN NOT NULL,
    ip_origen       VARCHAR(255),
    fecha_intento   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
